upgrade vim/pack

diff --git a/config/bash/bashrc b/config/bash/bashrc
--- a/config/bash/bashrc
+++ b/config/bash/bashrc
@@ -1,3 +1,5 @@
+# .bashrc
+
 if [ -x /usr/libexec/path_helper ]; then
     eval `/usr/libexec/path_helper -s`
 fi
@@ -7,11 +9,27 @@ if [ -f /etc/bashrc ]; then
     . /etc/bashrc
 fi
 
+shopt -s extglob
+
+# check the window size after each command and, if necessary, update the values
+# of LINES and COLUMNS.
+shopt -s checkwinsize
+
 export HISTFILE=~/.bash_sessions/.bash_history_${ITERM_SESSION_ID%:*}
+
+function prompt {
+	PS1=$("${HOME}/dotfiles/bin/prompt" $? "${SHLVL}" "${SSH_TTY}")
+}
+
+PROMPT_DIRTRIM=3
+export PROMPT_COMMAND=prompt
 
 ######################################
 ### SET PATHS AND EDITORS AND SUCH ###
 ######################################
+
+export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
+export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
 
 export XDG_CONFIG_HOME="${HOME}/dotfiles/config"
 export XDG_CACHE_HOME="${HOME}/dotfiles/cache"
@@ -24,7 +42,6 @@ export HOMEBREW_NO_ANALYTICS=1
 # Go
 export GOPATH="${HOME}/gopath"
 export GOBIN="${GOPATH}/bin"
-export GO111MODULE=on
 
 # Editors and such.
 export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
@@ -64,13 +81,6 @@ fi
 export CLICOLOR=1
 export TERM=xterm-256color
 export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
-
-function prompt {
-	PS1=$("${HOME}/dotfiles/bin/prompt" $? "${SHLVL}", "${SSH_TTY}")
-}
-
-PROMPT_DIRTRIM=3
-export PROMPT_COMMAND=prompt
 
 # Colored man pages:
 export LESS_TERMCAP_mb=$(tput bold; tput setaf 1)
@@ -118,31 +128,129 @@ alias nents='ls -1 | wc -l | sed "s#[[:space:]]##g"'
 ### FUNCTIONS ###
 #################
 
-# Performs ls -l on cd
+function tree_size {
+	find -x . -type f -exec sh -c 'stat -f '%z' "${@}"' _ '{}' + | \
+		LC_ALL=C awk -v pwd="${PWD}" '
+		BEGIN{ sum=0; count=0; }
+		{ sum+=$1; ++count; }
+		END{ 
+			if (count == 0) exit;
+			printf ("directory: %s\n", pwd); 
+			printf ("number of files: %d\n", count); 
+			printf ("total size: %.f MiB\n", sum / (1024*1024))
+			printf ("average file size: %.5f B\n", sum/count); 
+			printf ("                 : %.5f kiB\n", (sum/count) / 1024); 
+			printf ("                 : %.5f MiB\n", (sum/count) / (1024*1024)); 
+		}
+		'
+}
 
+function line {
+	head -n+"${1}" < "${2}" | tail -1
+}
+
+# cd erforms ls -l on cd.
 function cd {
     dir="${@:-$HOME}"  # ~ isn't expanded when in quotes
     [[ -z "${dir}" ]] && dir=~
-    if ! builtin cd "$dir"; then
+    if ! builtin cd "${dir}"; then
 		dir=$(compgen -d "${dir}" | head -1)
-        if builtin cd "$dir"; then
-            clear ; pwd ;ls -l
+        if builtin cd "${dir}"; then
+            clear ; pwd ; ls -l
         fi
     else
         clear ; pwd ; ls -l
     fi
 }
 
-ed() { command ed -p\* "$@" ; }
+function ed { command ed -p\* "$@" ; }
 
-###########################################
-## This does something important I think ##
-###########################################
+function share {
+	if [[ -z "${1}" ]]; then
+		echo "parameter required"
+		return 0
+	fi
 
-shopt -s extglob
+	if [[ -z "${SHARE_BACKEND}" ]]; then
+		echo "SHARE_BACKEND unset or empty"
+		return 0
+	fi
 
-# check the window size after each command and, if necessary, update the values
-# of LINES and COLUMNS.
-shopt -s checkwinsize
+	open \
+		-a 'SpiderOak Share.app' \
+		-n \
+		--args \
+		--ignore-locking \
+		--data-folder-name "${1}"
+}
+
+function gitcmd {
+	if [[ "${2}" != "commit" ]]; then
+		git "${@}"
+		return $?
+	fi
+
+	git commit -m "X" &> /dev/null 
+	if [[ ! "${?}" -eq 0 ]]; then
+		git commit --amend
+	fi
+	return $?
+}
+
+###################
+### SET ALIASES ###
+###################
+
+alias git='gitcmd '
+
+alias utests='go test -v -short -failfast $(go list ./... | grep -v "/tr") '
+
+alias gprof='go tool pprof -http :9999 '
+alias gtrace='go tool trace '
+
+# yubikey
+alias keyon='osascript -e '\''tell application "yubiswitch" to KeyOn'\'''
+alias keyoff='osascript -e '\''tell application "yubiswitch" to KeyOff'\'''
+
+# last file in directory
+alias last='find . -maxdepth 1 -type f -print0 | \
+	xargs -0 stat -f "%m %N" | \
+	sort -rn | \
+	head -1 | \
+	cut -f2- -d" "'
+
+# rg
+alias rgi='rg -i '
+alias rgg='rg --type=go '
+alias rgig='rgg -i '
+alias rgc='rg --type=c '
+alias rgic='rgc -i '
+alias ag='rgi '
+
+# etc.
+alias ls='ls -G'
+alias h?='history | grep -i '
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias .....='cd ../../../..'
+alias ......='cd ../../../../..'
+alias .......='cd ../../../../../..'
+alias ........='cd ../../../../../../..'
+alias .........='cd ../../../../../../../..'
+alias pong="ping 8.8.8.8 -c 4"
+alias myip='curl -s icanhazip.com'
+alias gerp='grep'
+alias tial='tail'
+alias lsa='ls -a'
+alias lsal='ls -al'
+alias lsl='ls -l'
+alias nents='ls -1 | wc -l | sed "s#[[:space:]]##g"'
+
+###########
+### ETC ###
+###########
 
 [ -f ~/.fzf.bash ] && source ~/.fzf.bash
+
+eval "$(direnv hook bash)"
